/**
 * Convex API
 * 
 * This file re-exports the generated Convex API for use throughout the application.
 * 
 * Note: The actual API interface is generated by Convex and this file only provides a convenient import point.
 */

import { api } from "../../convex/_generated/api";

export { api }; 